Repository SUVID-18/check_attendance_professor, pull requests merged in 2023-11, with the labels that each got.

#29 feature/3
  lib/view/attendance_management.dart
  lib/view/styles.dart
  lib/view/subjects_page.dart
  pubspec.lock
Labels: enhancement

#31 pm/auto_ci
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/pull_request_template.md
  .github/workflows/flutter-deploy.yaml
  .github/workflows/flutter-test.yaml
Labels: 기능 개선

#34 optimization
  lib/main.dart
  lib/view/main_page.dart
  lib/view/subjects_page.dart
  test/widget_test.dart
Labels: 기능 개선

#32 pm/auto_ci
  .github/workflows/flutter-deploy.yaml
  .github/workflows/make_api_document.yml
Labels: bug

#35 feature/12
  lib/model/subject.dart
  lib/view_model/attendance_management.dart
  lib/view_model/subject_page.dart
  test/subject_test.dart
Labels: bug, 기능 개선

#37 feature/13
  lib/main.dart
  lib/model/lecture.dart
  lib/view/attendance_management.dart
  lib/view/settings_page.dart
  lib/view/subject_settings.dart
  lib/view_model/attendance_management.dart
  lib/view_model/settings.dart
  lib/view_model/subject_page.dart
  lib/view_model/subject_settings.dart
  test/model_test.dart
  test/widget_test.dart
Labels: 기능 개선

#38 hotfix/start_time
  lib/view/subject_settings.dart
  lib/view_model/subject_settings.dart
Labels: bug

#39 release/v1.0
  .github/workflows/flutter-deploy.yaml
  .github/workflows/flutter-preview.yaml
  lib/main.dart
  lib/model/lecture.dart
  lib/model/subject.dart
  lib/view/attendance_management.dart
  lib/view/main_page.dart
  lib/view/register_page.dart
  lib/view/settings_page.dart
  lib/view/styles.dart
  lib/view/subject_settings.dart
  lib/view/subjects_page.dart
  lib/view_model/attendance_management.dart
  lib/view_model/settings.dart
  lib/view_model/subject_page.dart
  lib/view_model/subject_settings.dart
  pubspec.lock
  pubspec.yaml
  test/model_test.dart
  test/subject_test.dart
  test/widget_test.dart
Labels: 기능 개선
